export type FactPoint = {
  year: number;
  value: number;
  display: string;
};

export type FactMetric = {
  value: string;
  label: string;
  period: string;
};

export type FactEntry = {
  slug: string;
  topic: string;
  question: string;
  title: string;
  description: string;
  answer: string;
  value: string;
  valueLabel: string;
  period: string;
  unit: string;
  accent: string;
  evidence: string;
  observed: string;
  policy: string;
  limitation: string;
  definition: string;
  sourceName: string;
  sourceOrganization: string;
  sourceUrl: string;
  sourceChecked: string;
  metrics?: FactMetric[];
  points?: FactPoint[];
  related: string[];
};

export const facts: FactEntry[] = [
  {
    slug: 'vardgarantin-2026',
    topic: 'Sjukvård',
    question: 'Hur många får vård inom vårdgarantin?',
    title: 'Vårdgarantin i Sverige 2026',
    description: 'Aktuell statistik om hur stor andel som får kontakt, bedömning, specialistbesök och operation inom vårdgarantins tidsgränser.',
    answer: 'I juni 2026 fick 71 procent operation eller åtgärd inom 90 dagar. Ingen av vårdgarantins fyra delar nådde 100 procent.',
    value: '71 %',
    valueLabel: 'operation eller åtgärd inom 90 dagar',
    period: 'Juni 2026',
    unit: 'andel patienter',
    accent: '#0f7f77',
    evidence: 'Hög säkerhet om utfallet · låg om ensam politisk orsak',
    observed: '93 procent fick första kontakt samma dag, 90 procent medicinsk bedömning inom tre dagar, 80 procent första specialistbesök inom 90 dagar och 71 procent operation eller åtgärd inom 90 dagar.',
    policy: 'Regionernas resurser, arbetssätt, bemanning och statliga styrmedel kan påverka väntetiderna.',
    limitation: 'En månads nationella utfall visar inte effekten av en viss reform. Regioner som byter journalsystem kan dessutom ha påverkad rapportering.',
    definition: 'Måtten avser andelen patienter som fått vård inom de lagstadgade tidsgränserna. Socialstyrelsens nya väntetidsdatabas innebär ett seriebrott från juli 2025.',
    sourceName: 'Tillgänglighet, väntetider och vårdgaranti',
    sourceOrganization: 'Socialstyrelsen',
    sourceUrl: 'https://www.socialstyrelsen.se/statistik-och-data/statistik/alla-statistikamnen/lagesbild-och-statistik-tillganglighet-vantetider-och-vardgaranti-i-halso-och-sjukvard/',
    sourceChecked: '27 augusti 2026',
    metrics: [
      { value: '93 %', label: 'första kontakt samma dag', period: 'juni 2026' },
      { value: '90 %', label: 'medicinsk bedömning inom 3 dagar', period: 'juni 2026' },
      { value: '80 %', label: 'specialistbesök inom 90 dagar', period: 'juni 2026' },
      { value: '71 %', label: 'operation/åtgärd inom 90 dagar', period: 'juni 2026' },
    ],
    related: ['gymnasiebehorighet-2025', 'aldreomsorg-2025', 'hushallens-ekonomi-2024'],
  },
  {
    slug: 'gymnasiebehorighet-2025',
    topic: 'Skola',
    question: 'Hur många niondeklassare blev gymnasiebehöriga?',
    title: 'Gymnasiebehörighet efter årskurs 9',
    description: 'Senaste officiella utfallet för behörighet till gymnasiets yrkesprogram, med förklaringar och källa.',
    answer: '84,1 procent av eleverna var behöriga till ett nationellt yrkesprogram våren 2025.',
    value: '84,1 %',
    valueLabel: 'behöriga till gymnasiets yrkesprogram',
    period: 'Våren 2025',
    unit: 'andel elever',
    accent: '#4667b1',
    evidence: 'Hög säkerhet om nationellt utfall',
    observed: 'Skolverkets slutbetygsstatistik visar att 84,1 procent var behöriga till ett nationellt yrkesprogram våren 2025.',
    policy: 'Skolans resurser, lärarbehörighet, stödinsatser och kommunala prioriteringar kan påverka resultaten.',
    limitation: 'Elevsammansättning, föräldrars utbildning och lokala förutsättningar påverkar råa jämförelser. Senare resultat efter lovskola ingår inte i denna mätpunkt.',
    definition: 'Behörighet till yrkesprogram kräver godkända betyg i svenska eller svenska som andraspråk, engelska, matematik och minst fem andra ämnen.',
    sourceName: 'Slutbetyg i grundskolan våren 2025',
    sourceOrganization: 'Skolverket',
    sourceUrl: 'https://www.skolverket.se/download/18.7bc6fce31993221716f401af/1758550287766/pdf13315.pdf',
    sourceChecked: '27 augusti 2026',
    metrics: [
      { value: '84,1 %', label: 'behöriga till yrkesprogram', period: 'våren 2025' },
      { value: '24 sep', label: 'nästa ordinarie publicering', period: '2026' },
    ],
    related: ['vardgarantin-2026', 'arbetslosheten-2025', 'valet-2026'],
  },
  {
    slug: 'skjutningar-2026',
    topic: 'Lag & ordning',
    question: 'Har skjutningarna minskat under 2026?',
    title: 'Skjutningar och sprängningar 2026',
    description: 'Polisens preliminära statistik över bekräftade skjutningar och detonationer januari–juli 2026.',
    answer: 'Polisen registrerade 49 skjutningar januari–juli 2026, jämfört med 101 under samma period 2025.',
    value: '49',
    valueLabel: 'bekräftade skjutningar',
    period: 'Januari–juli 2026',
    unit: 'händelser',
    accent: '#d04d45',
    evidence: 'Preliminärt operativt utfall',
    observed: 'Antalet bekräftade skjutningar minskade från 101 till 49 mellan januari–juli 2025 och samma period 2026. Detonationer minskade från 123 till 71.',
    policy: 'Polisiära insatser, lagstiftning, konfliktdämpning, beslag och förebyggande arbete kan bidra till förändringen.',
    limitation: 'Den korta perioden och flera samtidiga insatser gör att utvecklingen inte kan tillskrivas en enskild regering eller reform.',
    definition: 'Polisens operativa sammanställning av bekräftade skjutningar och fullbordade sprängningar. Händelser kan omklassificeras när ny information tillkommer.',
    sourceName: 'Sprängningar och skjutningar',
    sourceOrganization: 'Polismyndigheten',
    sourceUrl: 'https://polisen.se/om-polisen/polisens-arbete/sprangningar-och-skjutningar/',
    sourceChecked: '27 augusti 2026',
    metrics: [
      { value: '49', label: 'skjutningar', period: 'jan–jul 2026' },
      { value: '101', label: 'skjutningar', period: 'jan–jul 2025' },
      { value: '71', label: 'detonationer', period: 'jan–jul 2026' },
      { value: '123', label: 'detonationer', period: 'jan–jul 2025' },
    ],
    related: ['dodligt-vald-2025', 'migration-och-brott', 'valet-2026'],
  },
  {
    slug: 'dodligt-vald-2025',
    topic: 'Brott & trygghet',
    question: 'Har det dödliga våldet minskat?',
    title: 'Dödligt våld i Sverige 2025',
    description: 'Konstaterade offer för dödligt våld i Sverige, med tidsserie, regeringskontext och tydlig metodgräns.',
    answer: 'Brå konstaterade 84 offer för dödligt våld 2025, åtta färre än året före.',
    value: '84',
    valueLabel: 'offer för dödligt våld',
    period: '2025',
    unit: 'offer',
    accent: '#e54e45',
    evidence: 'Hög säkerhet om utfallet · låg kausal evidens',
    observed: 'Antalet konstaterade offer minskade från 92 år 2024 till 84 år 2025.',
    policy: 'Polisens resurser, lagstiftning och förebyggande arbete kan påverka utvecklingen, ofta med fördröjning.',
    limitation: 'Tidsserien ensam visar inte att förändringen orsakades av en viss regering, straffskärpning eller polisinsats. Enskilda händelser kan påverka ett litet årsantal kraftigt.',
    definition: 'Fall där Brå efter manuell granskning bedömt att en person dödats genom brott. Måttet är inte samma sak som preliminära anmälningar om mord eller dråp.',
    sourceName: 'Konstaterade fall av dödligt våld',
    sourceOrganization: 'Brottsförebyggande rådet',
    sourceUrl: 'https://bra.se/statistik/statistik-om-rattsvasendet/konstaterade-fall-av-dodligt-vald',
    sourceChecked: '27 augusti 2026',
    points: [
      { year: 2018, value: 108, display: '108 offer' },
      { year: 2019, value: 111, display: '111 offer' },
      { year: 2020, value: 124, display: '124 offer' },
      { year: 2021, value: 113, display: '113 offer' },
      { year: 2022, value: 116, display: '116 offer' },
      { year: 2023, value: 121, display: '121 offer' },
      { year: 2024, value: 92, display: '92 offer' },
      { year: 2025, value: 84, display: '84 offer' },
    ],
    related: ['skjutningar-2026', 'migration-och-brott', 'arbetslosheten-2025'],
  },
  {
    slug: 'invandringen-2025',
    topic: 'Migration',
    question: 'Har invandringen till Sverige minskat?',
    title: 'Invandring till Sverige 2025',
    description: 'Registrerade invandringar till Sverige 2025 jämfört med tidigare år och vad måttet faktiskt omfattar.',
    answer: 'SCB registrerade 89 434 invandringar 2025, 23 procent färre än 2024.',
    value: '89 434',
    valueLabel: 'registrerade invandringar',
    period: '2025',
    unit: 'personer',
    accent: '#7857d8',
    evidence: 'Hög säkerhet om folkbokfört utfall',
    observed: 'Registrerade invandringar minskade från 116 197 år 2024 till 89 434 år 2025.',
    policy: 'Svenska regler påverkar vissa migrationsvägar. EU-rätt, krig, familjeband och arbetsmarknad verkar samtidigt.',
    limitation: 'Förändringen kan inte ensam tillskrivas den sittande regeringen eller en viss lag. Måttet säger inte hur integrationen senare utvecklas.',
    definition: 'Folkbokförda varaktiga flyttningar till Sverige. Återinvandrade svenskfödda ingår; asylansökningar och uppehållstillstånd är andra mått.',
    sourceName: 'Befolkningsutvecklingen i riket',
    sourceOrganization: 'Statistiska centralbyrån',
    sourceUrl: 'https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__BE__BE0101__BE0101G/BefUtvKon1749/',
    sourceChecked: '27 augusti 2026',
    points: [
      { year: 2018, value: 132602, display: '132 602' },
      { year: 2019, value: 115805, display: '115 805' },
      { year: 2020, value: 82518, display: '82 518' },
      { year: 2021, value: 90631, display: '90 631' },
      { year: 2022, value: 102436, display: '102 436' },
      { year: 2023, value: 94514, display: '94 514' },
      { year: 2024, value: 116197, display: '116 197' },
      { year: 2025, value: 89434, display: '89 434' },
    ],
    related: ['migration-och-brott', 'arbetslosheten-2025', 'valet-2026'],
  },
  {
    slug: 'arbetslosheten-2025',
    topic: 'Jobb & ekonomi',
    question: 'Har arbetslösheten ökat?',
    title: 'Arbetslösheten i Sverige 2025',
    description: 'SCB:s årsmedeltal för arbetslösheten och varför regeringsperioder inte automatiskt visar reformeffekter.',
    answer: 'Arbetslösheten var 8,8 procent 2025, upp från 8,4 procent året före.',
    value: '8,8 %',
    valueLabel: 'arbetslöshet bland 15–74 år',
    period: '2025',
    unit: 'procent',
    accent: '#e9912d',
    evidence: 'Officiellt utfall · låg kausal evidens',
    observed: 'Arbetslösheten steg med 0,4 procentenheter mellan 2024 och 2025.',
    policy: 'Skatter, utbildning och arbetsmarknadsåtgärder kan påverka, liksom finans- och penningpolitik.',
    limitation: 'Konjunktur, ränta, internationell efterfrågan och befolkningssammansättning verkar samtidigt. Årsserien är inte en effektutvärdering.',
    definition: 'AKU:s internationella definition: personer utan arbete som kan arbeta och aktivt söker arbete. AKU är en urvalsundersökning.',
    sourceName: 'Arbetskraftsundersökningarna',
    sourceOrganization: 'Statistiska centralbyrån',
    sourceUrl: 'https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__AM__AM0401__AM0401A/AKURLBefAr/',
    sourceChecked: '27 augusti 2026',
    points: [
      { year: 2018, value: 6.5, display: '6,5 %' },
      { year: 2019, value: 6.9, display: '6,9 %' },
      { year: 2020, value: 8.5, display: '8,5 %' },
      { year: 2021, value: 8.9, display: '8,9 %' },
      { year: 2022, value: 7.5, display: '7,5 %' },
      { year: 2023, value: 7.7, display: '7,7 %' },
      { year: 2024, value: 8.4, display: '8,4 %' },
      { year: 2025, value: 8.8, display: '8,8 %' },
    ],
    related: ['hushallens-ekonomi-2024', 'invandringen-2025', 'gymnasiebehorighet-2025'],
  },
  {
    slug: 'hushallens-ekonomi-2024',
    topic: 'Privatekonomi',
    question: 'Har hushållens ekonomiska standard återhämtat sig?',
    title: 'Hushållens ekonomiska standard',
    description: 'Median ekonomisk standard i fasta priser, med pris-, ränte- och fördelningsperspektiv.',
    answer: 'Median ekonomisk standard steg till 324 900 kronor under 2024 men låg fortfarande under nivån 2021.',
    value: '324,9 tkr',
    valueLabel: 'median ekonomisk standard',
    period: '2024 · fasta priser',
    unit: 'tkr per konsumtionsenhet',
    accent: '#1f8265',
    evidence: 'Hög säkerhet om medianen · variationen mellan hushåll är stor',
    observed: 'Medianen ökade från 319 100 kronor 2023 till 324 900 kronor 2024, men var lägre än 331 200 kronor 2021.',
    policy: 'Skatter, transfereringar och stöd påverkar disponibla inkomster. Löner, inflation, ränta och hushållssammansättning påverkar samtidigt.',
    limitation: 'Medianen visar mitten och döljer spridningen. Bolånetagare, hyresgäster, barnfamiljer och pensionärer kan ha helt olika utveckling.',
    definition: 'Disponibel hushållsinkomst justerad för hushållets storlek och uttryckt i fasta priser, exklusive kapitalvinster.',
    sourceName: 'Hushållens ekonomi',
    sourceOrganization: 'Statistiska centralbyrån',
    sourceUrl: 'https://www.statistikdatabasen.scb.se/pxweb/sv/ssd/START__HE__HE0110__HE0110F/TabVX1DispInkN/',
    sourceChecked: '27 augusti 2026',
    points: [
      { year: 2017, value: 316, display: '316,0 tkr' },
      { year: 2018, value: 319.3, display: '319,3 tkr' },
      { year: 2019, value: 321.9, display: '321,9 tkr' },
      { year: 2020, value: 323.7, display: '323,7 tkr' },
      { year: 2021, value: 331.2, display: '331,2 tkr' },
      { year: 2022, value: 322.2, display: '322,2 tkr' },
      { year: 2023, value: 319.1, display: '319,1 tkr' },
      { year: 2024, value: 324.9, display: '324,9 tkr' },
    ],
    related: ['arbetslosheten-2025', 'pensionens-ersattningsgrad', 'aldreomsorg-2025'],
  },
  {
    slug: 'pensionens-ersattningsgrad',
    topic: 'Pension',
    question: 'Hur stor del av lönen blir allmän pension?',
    title: 'Pensionens ersättningsgrad 2026',
    description: 'Pensionsmyndighetens mått på nyblivna pensionärers pension jämfört med inkomsten före pension.',
    answer: 'För medelinkomsttagare som tog ut pension vid 66 års ålder var medianen 58 procent för kvinnor och 60 procent för män.',
    value: '58–60 %',
    valueLabel: 'allmän pension jämfört med tidigare inkomst',
    period: 'Nyblivna pensionärer 2025',
    unit: 'median ersättningsgrad',
    accent: '#8d5b9e',
    evidence: 'Officiell kohortstatistik',
    observed: 'Median ersättningsgrad för allmän pension var 58 procent för kvinnor och 60 procent för män bland medelinkomsttagare som tog ut pension vid 66 års ålder.',
    policy: 'Indexering, pensionsålder, garantipension och skatter påverkar utfallet. Ett längre arbetsliv höjer normalt pensionen.',
    limitation: 'Kohorter, uttagsålder och tjänstepension skiljer sig. Måttet är inte samma sak som alla pensionärers faktiska ekonomiska standard.',
    definition: 'Pensionen jämförs med inkomsten före pension. Total pension inkluderar tjänstepension och redovisas med ett års extra eftersläpning.',
    sourceName: 'Nyblivna pensionärers kompensationsgrader 2026',
    sourceOrganization: 'Pensionsmyndigheten',
    sourceUrl: 'https://www.pensionsmyndigheten.se/statistik/publikationer/nyblivna-pensionarers-kompensationsgrader-2026/',
    sourceChecked: '27 augusti 2026',
    metrics: [
      { value: '58 %', label: 'allmän pension · kvinnor', period: '2025' },
      { value: '60 %', label: 'allmän pension · män', period: '2025' },
      { value: '68 %', label: 'total pension · kvinnor', period: '2024' },
      { value: '73 %', label: 'total pension · män', period: '2024' },
    ],
    related: ['hushallens-ekonomi-2024', 'aldreomsorg-2025', 'arbetslosheten-2025'],
  },
  {
    slug: 'aldreomsorg-2025',
    topic: 'Äldreomsorg',
    question: 'Får en mindre andel äldre hemtjänst?',
    title: 'Hemtjänst och äldreomsorg 2025',
    description: 'Andelen personer 65 år och äldre med hemtjänst och varför omfattning inte är samma sak som kvalitet.',
    answer: 'Andelen 65+ med hemtjänst minskade från 11,33 procent 2014 till 10,22 procent 2025.',
    value: '10,22 %',
    valueLabel: 'av personer 65+ med hemtjänst',
    period: '2025',
    unit: 'andel 65+',
    accent: '#4a7aa8',
    evidence: 'Officiellt omfattningsmått · inte ett kvalitetsmått',
    observed: 'Andelen med hemtjänst har sjunkit över perioden, samtidigt som befolkningen 65 år och äldre har vuxit.',
    policy: 'Kommunal biståndsbedömning, bemanning, statsbidrag, bostäder och förebyggande stöd kan påverka omfattningen.',
    limitation: 'Andelen visar inte väntetid, personalkontinuitet, upplevd kvalitet eller ouppfyllt behov. Antalet mottagare kan öka även när andelen sjunker.',
    definition: 'Andel folkbokförda personer 65 år och äldre med beviljad eller verkställd hemtjänst.',
    sourceName: 'Socialtjänstinsatser till äldre 2025',
    sourceOrganization: 'Socialstyrelsen',
    sourceUrl: 'https://www.socialstyrelsen.se/publikationer/statistik-om-socialtjanstinsatser-till-aldre-2025-2026-4-10218/',
    sourceChecked: '27 augusti 2026',
    points: [
      { year: 2018, value: 10.91, display: '10,91 %' },
      { year: 2019, value: 10.92, display: '10,92 %' },
      { year: 2020, value: 10.47, display: '10,47 %' },
      { year: 2021, value: 10.34, display: '10,34 %' },
      { year: 2022, value: 10.43, display: '10,43 %' },
      { year: 2023, value: 10.40, display: '10,40 %' },
      { year: 2024, value: 10.29, display: '10,29 %' },
      { year: 2025, value: 10.22, display: '10,22 %' },
    ],
    related: ['pensionens-ersattningsgrad', 'vardgarantin-2026', 'hushallens-ekonomi-2024'],
  },
  {
    slug: 'migration-och-brott',
    topic: 'Migration & brott',
    question: 'Vad visar Brå om migration och brott?',
    title: 'Migrationsbakgrund och brottsmisstanke',
    description: 'Brås historiska registerstudie, med observerade andelar, standardiserad överrisk och tydliga begränsningar.',
    answer: 'I den historiska kohorten registrerades 7,99 procent av utrikesfödda som misstänkta, jämfört med 3,18 procent i referensgruppen.',
    value: '7,99 %',
    valueLabel: 'utrikesfödda registrerade som minst skäligen misstänkta',
    period: 'Kohort 2014 · misstankar 2015–2018',
    unit: 'andel personer',
    accent: '#9e493d',
    evidence: 'Historisk deskriptiv association · inte migrationseffekt',
    observed: 'Den råa överrisken var 2,51. Efter standardisering för ålder, kön, disponibel inkomst, utbildning och kommuntyp var överrisken 1,77.',
    policy: 'Utbildning, arbetsmarknad, bostadssegregation, polisens arbetssätt och prevention kan påverka registrerad misstanke.',
    limitation: 'Misstänkt är inte dömd. Födelseland är inte etnicitet eller kultur. Studien visar inte nuläget 2026 och kan inte avgöra varför skillnaderna finns.',
    definition: 'Personer 15 år eller äldre som var folkbokförda den 31 december 2014 och registrerades som minst skäligen misstänkta för minst ett brott begånget 2015–2018.',
    sourceName: 'Misstänkta för brott bland personer med inrikes respektive utrikes bakgrund',
    sourceOrganization: 'Brottsförebyggande rådet',
    sourceUrl: 'https://bra.se/rapporter/arkiv/2021-08-25-misstankta-for-brott-bland-personer-med-inrikes-respektive-utrikes-bakgrund',
    sourceChecked: '27 augusti 2026',
    metrics: [
      { value: '7,99 %', label: 'utrikesfödda · rå andel', period: '2015–2018' },
      { value: '3,18 %', label: 'referensgrupp · rå andel', period: '2015–2018' },
      { value: '2,51×', label: 'observerad överrisk', period: 'historisk kohort' },
      { value: '1,77×', label: 'standardiserad överrisk', period: 'historisk kohort' },
    ],
    related: ['skjutningar-2026', 'dodligt-vald-2025', 'invandringen-2025'],
  },
  {
    slug: 'valet-2026',
    topic: 'Valet 2026',
    question: 'Hur många får rösta i valet 2026?',
    title: 'Röstberättigade i valet 2026',
    description: 'Valmyndighetens preliminära rådata över röstberättigade, förstagångsväljare och kommande resultatfiler.',
    answer: '8 046 725 personer är röstberättigade i riksdagsvalet 2026. Av dem är 483 182 förstagångsväljare.',
    value: '8 046 725',
    valueLabel: 'röstberättigade i riksdagsvalet',
    period: 'Valdagen 13 september 2026',
    unit: 'personer',
    accent: '#1d67f2',
    evidence: 'Valmyndighetens rådata',
    observed: 'Valmyndigheten redovisar 8 046 725 röstberättigade till riksdagen, 483 182 förstagångsväljare och 226 906 röstberättigade utlandssvenskar.',
    policy: 'Reglerna för rösträtt och folkbokföring bestämmer vilka som ingår. Partiernas mobilisering kan påverka det slutliga valdeltagandet.',
    limitation: 'Antalet röstberättigade säger inte hur högt valdeltagandet blir eller hur rösterna fördelas.',
    definition: 'Röstberättigade enligt Valmyndighetens preliminära rådata inför valen till riksdag, region och kommun 2026.',
    sourceName: 'Rådata val 2026',
    sourceOrganization: 'Valmyndigheten',
    sourceUrl: 'https://www.val.se/valresultat-och-statistik/statistik-och-data/radata-val-2026',
    sourceChecked: '27 augusti 2026',
    metrics: [
      { value: '8 046 725', label: 'röstberättigade till riksdagen', period: '2026' },
      { value: '483 182', label: 'förstagångsväljare', period: '2026' },
      { value: '226 906', label: 'röstberättigade utlandssvenskar', period: '2026' },
      { value: '13 sep', label: 'valdag', period: '2026' },
    ],
    related: ['vardgarantin-2026', 'skjutningar-2026', 'gymnasiebehorighet-2025'],
  },
];

export const factBySlug = Object.fromEntries(facts.map((fact) => [fact.slug, fact])) as Record<string, FactEntry>;

export const featuredFactSlugs = [
  'vardgarantin-2026',
  'skjutningar-2026',
  'gymnasiebehorighet-2025',
  'hushallens-ekonomi-2024',
  'valet-2026',
];

export const featuredFacts = featuredFactSlugs.map((slug) => factBySlug[slug]);

export const factPath = (slug: string) => `/fakta/${slug}`;
